version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: urlshortener
    ports:
      - "5433:5432"  # Change the host port if necessary

  web:
    build: .
    command: ["gunicorn", "urlshortener.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
